from my_package.xyz import  
def main(dir="", name):
    with open(f"{mol}.minfo", "w", encoding="UTF-8") as f:
    f.write("[ Atomic Data ]\n")
    f.write(str(atom_num) + "\n")
    for line in atomic_xyz:
        f.write(f" {line}\n")
    f.write("\n")
    f.write("[ Electronic Data ]\n")
    f.write("Energy\n")
    f.write(str(energy))
    f.write("\nCharge\n")
    f.write(str(charge))
    f.write("\nMultiplicity\n")
    f.write(str(mult))
    f.write("\nGradient\n")
    f.write(str(atom_num*3))
    f.write("\n")
    f.write(grad)
    f.write("\n")
    f.write("Hessian\n")
    f.write(str(int(atom_num**2*(atom_num**2+1)/2)))
    f.write("\n")
    f.write(upper_triangle)
    f.write("\nDipole Moment\n3\n")
    f.write(di_moment)
    f.write("\nPolarizability\n")
    f.write("6\n")
    f.write(pol)
    f.write("\n")
    f.write("Dipole Derivative\n")
    f.write(str(atom_num*3*3))
    f.write("\n")
    f.write(dipole)
    f.write("\n[ Vibrational Data ]")
    f.write("\nNormal modes")
    f.write("\nTranslational Frequency\n")
    f.write("3\n")
    f.write(trans)
    f.write("\nTranslational vector\n")
    for i, val in enumerate(tra_modes):
        f.write(f"T {i+1}\n")
        f.write(str(atom_num*3))
        f.write("\n")
        v = "\n".join(", ".join(str(x) for x in val[i:i+5]) for i in range(0, len(val), 5))
        f.write(v)
        f.write("\n")
    f.write("\nRotational Frequency\n")
    f.write(f"{rot_num}\n")
    f.write(rotat)
    f.write("\nRotational vector\n")
    for i, val in enumerate(rot_modes):
        f.write(f"R {i+1}\n")
        f.write(str(atom_num*3))
        f.write("\n")
        v = "\n".join(", ".join(str(x) for x in val[i:i+5]) for i in range(0, len(val), 5))
        f.write(v)
        f.write("\n")
    f.write("\nVibrational Frequency\n")
    f.write(f"{len(vib_modes)}")
    f.write("\n")
    f.write(vibra)
    f.write("\nVibrational vector\n")
    for i, val in enumerate(vib_modes):
        f.write(f"Mode {i+1}\n")
        f.write(str(atom_num*3))
        f.write("\n")
        v = "\n".join(", ".join(str(x) for x in val[i:i+5]) for i in range(0, len(val), 5))
        f.write(v)
        f.write("\n")        
    


if __name__ == "__main__":
    dir = input("Specify the directory where the ORCA output files are located.")
    name = input("Specify the name of the ORCA output file.")
    print(f"Start the process with the file : {dir}{name}.__")
    main()

